### ISSUE TITLE
Failed to resolve ai.recast

### ISSUE THREAD

**Issue by dattu046** [RecastAI/SDK-Android#4]
When i add the dependency in the build.gradle file, the sync throws an error saying that it cannot resolve ai.recast. Please suggest me any fixes for this issue.

**Comment by phanii** [comment]
i am also getting the same

**Comment by dbousque** [comment]
Hey, sorry but this repo is no longer supported, we should archive it. I invite you to use the API directly instead, it is fairly simple to use. Here is the documentation for the bot-builder endpoint for example : https://recast.ai/docs/api-reference/#dialog-text

**Comment by phanii** [comment]
here is my sample request .. pls correct if its wrong. but im unable to get the response
https://www.getpostman.com/collections/b742fdc35c9c88b7be25

**Comment by phanii** [comment]
### i tried https://www.getpostman.com/collections/b742fdc35c9c88b7be25 but unable to get the response
pls correct with the valid request/response

**Comment by dbousque** [comment]
Man, just take a look at the documentation, an example is provided : https://recast.ai/docs/api-reference/#dialog-text
The example provided :
```
curl -X POST "https://api.recast.ai/build/v1/dialog" \
       -H "Authorization: Token REQUEST_TOKEN" \
       -H "Content-Type: application/json" \
       -d '{"message": {"content":"Hello Recast","type":"text"}, "conversation_id": "CONVERSATION_ID"}'
```
